### ISSUE TITLE
Scrolling the cms licences view is broken

### ISSUE THREAD

**Issue by janhenckens** [pixelandtonic/craftnet#120]
On https://id.craftcms.com/licenses/cms vertical scrolling is broken, making the any item below the fold unreachable.

**Comment by angrybrad** [comment]
@janhenckens i'm not able to reproduce that locally on the latest Chrome. What browser/version/OS are you using?

**Comment by janhenckens** [comment]
Should have added that, sorry! I'm on the latest Firefox (64.0.2) on Mac OS Mojave.

**Comment by angrybrad** [comment]
@janhenckens ahh, i can reproduce there. thanks!

**Comment by angrybrad** [comment]
Fixed in https://github.com/pixelandtonic/craftnet/commit/d2c8475c28cacdf2596eaf99816b398cae4158ac
