### ISSUE TITLE
Add SEO data to the plugin store plugin links

### ISSUE THREAD

**Issue by khalwat** [pixelandtonic/craftnet#123]
If I tweet out a link to one of my plugins, or post it in Slack, it'd be nice if it had a good SEO title, description, and image (maybe the plugin icon or a screenshot I choose). Right now, it looks like this:

https://plugins.craftcms.com/seomatic

![slackscreensnapz225](https://user-images.githubusercontent.com/7570798/51397339-00990b00-1b0f-11e9-9a9e-a6adf8ffa132.png)

(with no Twitter/OG image either)

If these links are to become the canonical URL for plugins (which I think they should be), this would be great to have.

Since the plugin store is a Nuxt / Vue app, you'll be using: 

https://github.com/declandewet/vue-meta

...since Nuxt already uses it: https://nuxtjs.org/api/pages-head/

btw, you can also use vue-meta directly for the Craft CMS docs as well, since they are done in VuePress:

https://vuepress.vuejs.org/config/#description

(check out the https://vuepress.vuejs.org/config/#head **head** where you can add arbitrary links)

**Comment by benjamindavid** [comment]
The Plugin Store now uses [declandewet/vue-meta](https://github.com/declandewet/vue-meta) to provide OG/Twitter data. Thanks, @khalwat!
