### ISSUE TITLE
Incorrect Craft renewal price on public plugin store

### ISSUE THREAD

**Issue by alexjcollins** [pixelandtonic/craftnet#128]
Hey, wasn't sure where to put this but craftnet seemed the most appropriate...

The Craft CMS renewal price is incorrect at the bottom of the publicly facing plugin store.

🤑

![screenshot 2019-02-08 at 11 51 06](https://user-images.githubusercontent.com/12031196/52497911-3a6da680-2bcf-11e9-87e8-f7721883f5ba.png)

**Comment by angrybrad** [comment]
Oops... fixed!
