### ISSUE TITLE
[FR] Add styling to tables

### ISSUE THREAD

**Issue by kjmartens** [pixelandtonic/craftnet#130]
<img width="1465" alt="screen shot 2019-02-12 at 11 47 01 am" src="https://user-images.githubusercontent.com/1821674/52656471-15718000-2ebc-11e9-8883-7eef1bc43760.png">

It would be nice if Plugin Store markdown could display some sort of styling on tables. :)

**Comment by benjamindavid** [comment]
Should be fixed now. Thanks for reporting!

**Comment by kjmartens** [comment]
Delicious, thanks! 😄
