### ISSUE TITLE
Pagination for Sales in Craft ID

### ISSUE THREAD

**Issue by kjmartens** [pixelandtonic/craftnet#132]
It'd be nice if there were pagination and better searching/filtering control. Now that almost a full year has gone by it's getting hard to search the purchases, and I end up relying more and more on simple browser page searches. 😄

**Comment by benjamindavid** [comment]
Yeah, the situation got a bit complicated in the Sales section. Pagination has just been added to those listings, and we are hoping to add date filtering and other options along the way. Thank you @kjmartens!
