### ISSUE TITLE
Nexcess Cloud dev domains

### ISSUE THREAD

**Issue by croxton** [pixelandtonic/craftnet#134]
Any chance you could add `nxcli.net` to the list of dev domains in `config/dev-domains.php`? 

Nexcess Cloud assigns these automatically and they are typically used for development / staging.

Many thanks!

**Comment by angrybrad** [comment]
Done: https://github.com/pixelandtonic/craftnet/commit/b7b7c984cd7ef3c732541285c21575c7d9e2ef89
