### ISSUE TITLE
Improve Quality of Verification Process

### ISSUE THREAD

**Issue by lindseydiloreto** [pixelandtonic/craftnet#141]
Currently, getting a plugin approved is a largely manual process. A developer submits their plugin, then waits for about 24 hours while the plugin is "Pending Approval". It's great that the plugin submission is being viewed by a real human before being accepted into the plugin store, but the bar for acceptance seems to be painfully low.

One of Craft's greatest strengths is the high quality of its software and ecosystem, and the current plugin approval process is not safeguarding that critical distinction. I'm posting this because I (and others) care about maintaining that level of quality, and would hate to see the respectability of the Plugin Store decline over time.

I don't generally try to name names, but I feel it's important to show examples here...

## Many plugins lack a description

This is the most egregious, and most common, issue. Some developers apparently can't be bothered to write even a few sentences which describe the purpose of their plugin. This is beginning to leave the Plugin Store littered with indescribable (literally) plugins, that offer no obvious value to anyone.

For dedicated viewers, they can usually click the "Documentation" link to read more about the plugin, but _this puts the onus on the reader_. Adding extra steps to learn _literally anything_ about the plugin often adds up to a waste of our time, and doesn't do anything to inspire confidence in the plugin or its developer.

<https://plugins.craftcms.com/squeeze>
<https://plugins.craftcms.com/sharedcount>
<https://plugins.craftcms.com/vcard>

To be clear, I'm not saying that any of those are bad plugins! I'm emphasizing that the quality control of the Plugin Store shouldn't allow for plugins to be submitted without a description.

## Sometimes a plugin's "Documentation" link is broken

Granted, I've only seen this once. And it was doubly-offensive because the plugin _also_ lacked a description. Once the issue was reported (2 days later), P&T took steps to correct the link. But I have to wonder... couldn't this have been avoided by simply checking the link before approving the plugin?

## Plugins which add no significant value

There are a few plugins which would be better served as custom modules. Occasionally a developer will simply spin up a quick plugin using pluginfactory.io, then post it to the Plugin Store with little-to-no polish behind it. There should be some sort of reasonable bar set, where the plugin must actually be _generally useful_ to be included in the Plugin Store.

It's worth noting that the bar for "significant value" can be kept reasonably low. A plugin can add a small amount of value (ie: Twig Perversion) and clear the bar for being "generally useful". I'm mainly singling out plugins which have a tiny, nearly-unique purpose.

Keep in mind, it is fully possible to publish a "helper" plugin without adding it to the Plugin Store. Composer does not require that your plugins are downloaded from the store.

<https://plugins.craftcms.com/twig-dig>
<https://plugins.craftcms.com/time-ago>

## Don't violate the license of other plugins

There was a report recently of a plugin being submitted which was largely a copy of another developer's plugin. Fortunately this seems to be extremely rare, and I assume that P&T would be willing to get involved to sort out any issues between the two developers. I trust that P&T already takes this issue seriously, and intends to handle it on a case by case basis.

---

I apologize if I've offended anyone in the compilation of these issues. My intent is purely to **retain a medium-to-high level of quality within the Plugin Store**.

We all know what the WordPress plugin landscape looks like, and it's an utter disaster. Let's be better than that. If the Plugin Store is really going to operate as a "walled garden", then there should be some reasonable safeguards in place to make sure the overall quality remains respectable.

Thanks for your consideration. ❤️

**Comment by AbbeyDesign** [comment]
I would also appreciate having some sort of rating system and comments. I have run into installing a plugin or two that just didn't work very well or had some gotcha's. I need to know that kind of stuff before installing.

**Comment by AbbeyDesign** [comment]
I also need to know if a plugin is going to boink my site. I don't know if P&T tests this kind of stuff before a plugin is allowed to reside in the store.

**Comment by lindseydiloreto** [comment]
Thanks for weighing in @AbbeyDesign! While I agree with all of that, I really meant to focus this issue on the _manual_ review process. IE: What does the human verify before approving the plugin?

Rumor has it that P&T will eventually add a comments and/or ratings system to the plugin store. I think that will be awesome and very helpful, but it goes a bit beyond the intended scope of this issue. 🙂

**Comment by jalendport** [comment]
Totally agree with Lindsey 👍 

Just wanted to expound slightly on one of his statements:
> Adding extra steps to learn literally anything about the plugin often adds up to a waste of our time, and doesn't do anything to inspire confidence in the plugin or its developer.

In my opinion, a plugin developer should only add his plugin to the store if he has polished it to a certain degree and if he has spent an appropriate amount of time on the documentation (and I would argue maybe even on the brand/icon, but that's purely personal opinion); for example, take Verbb, nystudio107, or Working Concept (just a couple examples that came to mind, I'm sure there are more of you all out there): I can tell based on their plugins' info in the Plugin Store (and even if I click through to the README) that these plugins are solid, well-built, well-documented, and the plugin developer has really put an appropriate amount of polish and time into the plugins.

By `appropriate amount of time` I mean whatever would be expected based on your plugin's size/price/features. At the minimum, it should include throwing several sentences together for a description: "This is what my plugin does. This is what it doesn't do. This is how you use it." Not to toot my own horn, but I think my [Roman](https://plugins.craftcms.com/roman) plugin is possibly a good example of what one might expect a free plugin to look like. When I don't see a description or even if there is no plugin icon, it scares me a little as to how the plugin will function (once I figure out what it does and if it will solve my need).

I also just want to stress that I'm aiming as well for better quality in the store. I'm not saying Pixel & Tonic should spend their time reviewing every plugin's code and info to perfection, but rather like Lindsey said, I don't want the Craft plugin store to look like the Wordpress plugin "store". I think though, at the rate the store is growing, if efforts aren't made to enforce at least a very low level of quality, it will grow into a bigger problem eventually.

Was not my intention to offend any plugin developers or Pixel & Tonic on the current state of things, but just my 2¢ on the subject ¯\_(ツ)_/¯

**Comment by brandonkelly** [comment]
> There should be some sort of reasonable bar set, where the plugin must actually be generally useful to be included in the Plugin Store.

@lindseydiloreto Sorry but I completely disagree with that. We should not be policing plugins based on our perceived value, and wouldn’t have the resources if we wanted to. Even Apple doesn’t (or can’t) do that with the iOS App Store.

If a plugin meets our basic requirements, and appears to be following the [terms](https://craftcms.com/terms-of-use#developer-terms), we’re going to allow it.

Whether it’s of any use to you is a separate concern, which can be solved in three ways, post-verification:

- Metrics (active installs, GitHub issue stats, etc.)
- User feedback (ratings & reviews)
- P&T curation (featured plugins, editorial content)

We have work to do on those fronts, obviously.

> I'm emphasizing that the quality control of the Plugin Store shouldn't allow for plugins to be submitted without a description.

We’d have to start rejecting some of our own plugins if that were the case. That said we do require a short description, and we will start showing that in place of a long description if none exists.

> Sometimes a plugin's "Documentation" link is broken

The one time that happened, it was reported (I think by you?) and we fixed it. We have started checking that as part of the review process. And we’re going to make it easier to report plugin issues.

> There was a report recently of a plugin being submitted which was largely a copy of another developer's plugin.

The only IP violation case we are aware of is for a plugin that has not been submitted for approval yet, which we understand has been resolved at this point. We can’t possibly check for IP/license violations for each plugin submission, but this is also part of the reason we are going to make it easier to report issues.

> I apologize if I've offended anyone in the compilation of these issues. My intent is purely to retain a medium-to-high level of quality within the Plugin Store.

Appreciate your concerns, and to be clear we do agree it’s important that the Plugin Store is an effective place to discover quality plugins. Just don’t think that the approval process is where that should happen.

**Comment by AbbeyDesign** [comment]
Newest plugin "Download Assets" docs goes to a 404

**Comment by brandonkelly** [comment]
🤦‍♂️

**Comment by lindseydiloreto** [comment]
Set aside the "significant value" requirement. I agree that it's subjective (even though I think there's a reasonable bar that could be set).

Set aside the license violation requirement. I agree that this is hard to police, and I trust that P&T is willing to take corrective action retroactively.

Let's focus on **lack of description** and **broken documentation links**... These are both minor issues which are easily discoverable at the time of review.

<https://plugins.craftcms.com/download-assets>

^ This plugin was approved _literally last night_, and the documentation link is broken. That seems like a very basic step in the manual review process. It's good to hear that you will be checking this more vigorously moving forward.

A lack of description is one of the most frustrating things to consistently see in the plugin store. I know I'm not alone in this...

<img width="613" alt="2019-03-06 at 6 26 32 am" src="https://user-images.githubusercontent.com/5309692/53888272-ea6cde80-3fd8-11e9-9f0d-0c25354b1664.png">

It's also worth noting that this particular Github issue has garnered over 20 upvotes in less than 24 hours. This is clearly something that the community cares about, and feels is currently lacking.

>We’d have to start rejecting some of our own plugins if that were the case.

^ In which case, I'd highly recommend taking a few extra minutes to type up (or copy/paste) _something_. This is a pain point for users of the plugin store. 

> That said we do require a short description, and we will start showing that in place of a long description if none exists.

I guess this is sufficient. It's certainly better than nothing.

All of this leads me to wonder... "What _does_ happen during the manual review process?" If basic things like a description and link to documentation aren't being verified... what actually is?

Sorry to be so persistent about this. Again, my intention is to help the Plugin Store remain _healthy_ and _useful_ over the long term... it would be shame to see fairly minor issues contribute to a downward slide.

**Comment by sjelfull** [comment]
Yeah, there is a bunch of plugins that have had broken documentation links recently.

**Comment by brandonkelly** [comment]
> https://plugins.craftcms.com/download-assets
> 
> ^ This plugin was approved literally last night, and the documentation link is broken. That seems like a very basic step in the manual review process. It's good to hear that you will be checking this more vigorously moving forward.

Actually it was this morning at 3:26am, by myself, while sitting with a puppy that wouldn’t sleep due to something being stuck in its throat. I checked that the branch was correct (which was the issue with the previously reported incorrect docs URL) but should have just opened the link, as in this case it was the entire repo name was wrong (usually something GH 301 redirects for anyway, but in this case did not for whatever reason). Will open links going forward. And again, if you come across an issue, just let us know and we’ll fix right away.

> All of this leads me to wonder... "What does happen during the manual review process?" If basic things like a description and link to documentation aren't being verified... what actually is?

We make sure it’s actually a Craft plugin, make sure the LICENSE.md has the correct license in it, make sure Changelog Path is actually a path (e.g. `CHANGELOG.md`) and not a URL, and a quick gut check. Going forward we will open the changelog URL as well, and we intend to automate as much of this as we can going forward, especially as submission volume keeps going up. Eventually we hope to automate the installation of plugins to verify it’s actually a plugin, at which point we will kill the manual approval process entirely.

**Comment by lindseydiloreto** [comment]
Excellent, thanks for breaking down the approval process @brandonkelly. It's nice to know exactly what's taking place behind the scenes during the approval process. It sounds like steps are being taken to address the two main concerns (description & docs links).

And thanks for taking the time to discuss the matter. I appreciate your openness and honesty, and the level of transparency that P&T typically provides. I'm not sure I say it enough, but I'm very proud to be a member of this community.

Hope your puppy feels better. ❤️

**Comment by jalendport** [comment]
Thanks for your response, @brandonkelly. Appreciate all that you and the rest of the Pixel & Tonic team do, and honestly, I'm happy with whatever decisions you all have made or choose to make regarding the plugin approval process and what that looks like. Definitely not criticizing the current approval process _at all_; appreciate it that you're approving plugins at 3AM in the morning 😅

I think I would disagree with @lindseydiloreto about the broken links issue. That is usually a result of human error: a typo, they renamed their branch/repo, or something else (the one that I remember that was reported to P&T: they had changed their repo name slightly and forgot to update the links in the `composer.json`, which is totally understandable imo). Case and point: I made some small Composer/Packagist goofs submitting my first plugin to the store and @angrybrad was kind enough to patiently assist me as I resolved those. Like Brandon said, P&T have been super responsive at fixing any broken links in the plugin store, so I definitely do not think that is a super important issue at this point. Mistakes happen...

However, I still feel a description of some form or shape should be required. I would argue it's not in the same category as broken links because it's more like "I can't be bothered to add a description". I'm excited to hear that you're planning on using the short description as the _default/backup_, since as far as I know it's currently not even visible on the individual plugin detail pages. I think there may be other ways to solve it as well that won't require a more comprehensive review from the P&T team; for example, could the description field be a required field on `id.craftcms.com`? You could also add a small instruction blurb or placeholder to the field that reads something like _"We recommend adding a description to your plugin so people can quickly get an idea of what your plugin does and if it will help them."_ to encourage people to add a plugin description.

Again, just my humble opinion... Hope the puppy gets better @brandonkelly!

**Comment by kjmartens** [comment]
While I agree that it's frustrating to see a large number of plugins with poor descriptions and no screenshots, etc, I generally agree with @brandonkelly on this. Ultimately, if a plugin developer isn't willing to spend any time on their single most important marketing page, that should give you a taste of what kind of plugin you're potentially about to install. The developers that are serious about their product and supporting and maintaining it should intuitively know that they need to provide as much information as possible for their plugin page. We at Solspace have taken this very seriously ([Freeform for example](https://plugins.craftcms.com/freeform)) and will continue to make more improvements to our product pages.

In theory, the developers that choose to nurture their plugins and product pages should come out on top, above the other cruft. In addition to showing Install Counts (and them being more accurate), **Ratings and Reviews** would be the one other excellent and key addition to the Plugin Store to aid others that are considering purchasing/trying out that plugin. This could also allow you to order results by highest rated/most rated, etc.

My only complaints are that there does seem to be lacking _some_ basic styling currently, such as **table** styling, which makes a feature comparison chart like we included in [Freeform Pro](https://plugins.craftcms.com/freeform-pro) harder to read, unfortunately.

**Comment by lindseydiloreto** [comment]
@kjmartens I agree with 99% of what you said... the last 1% being, this ticket was written with the _consumer_ in mind.

>the developers that choose to nurture their plugins and product pages should come out on top

While this is true from a sales perspective, it misses the point from a consumer perspective. Many plugin shoppers aren't as savvy as you and I, and may not be so quick to pick up on the red flags of what is or isn't a quality plugin. Giving them an empty description with a broken documentation link is a disservice to someone who's simply trying to solve a problem.

Ratings and Reviews are an excellent (and common) suggestion, but this thread was intended to focus on the internal approval process done by a live human being. I agree that having those implemented will go a long way towards solving these other issues.

---

@jalendport Since the focus of this issue was on the human review process, I mentioned broken links as something simple for the human to be checking. Seems like an easy enough thing to do, there's no real benefit to skipping it.

Thankfully, P&T plans to test the documentation links more thoroughly moving forward, and has already implemented a fallback description. 👍

**Comment by kjmartens** [comment]
@lindseydiloreto I just think that if no one can truly tell what the product is, how are they even going to find it or know what it is, let alone choose to install it? 😆 And then presumably if most people don't find this product or know what it is, they likely won't install it, meaning that perhaps a slightly less savvy person would also see that the install count was "6" or something. Either way, I think this kind of thing sorts itself out. From a consumer perspective, I would be more concerned about a plugin that was overselling itself somehow with misleading info and had absolutely no indicator of its popularity, etc. There's also the fact that there are trials... so no money is lost really.

Further to this, I also think the demographic in the Craft community would be far more savvy about something like this than say, an iPhone user in the App Store.

That said, I agree that it's a shame there are so many plugins with poor descriptions and no screenshots, etc. It's a disservice to everyone as it's just cruft in the store. But if the ecosystem is very active, over time the garbage will fall to the bottom of the list, and people will be able to compare products and choose the one that appears much more promising/safe. 😊
