### ISSUE TITLE
Enlarged plugin images are tiny on smaller viewports

### ISSUE THREAD

**Issue by studiosyntax** [pixelandtonic/craftnet#147]
When browsing the plugin-store on mobile and clicking on a screenshot thumbnail, the enlargement is still quite small. Also zooming in with my fingers seems to be disabled. 

I know I could just open the images in a new tab, but that's not ideal when you want to quickly flick through the multiple provided screenshots.

**Comment by lindseydiloreto** [comment]
Agreed. Looking at screenshots on a phone is quite difficult (if not impossible).

**Comment by benjamindavid** [comment]
The situation should now be better on small screens. Thank you!

**Comment by studiosyntax** [comment]
And thank you!
