### ISSUE TITLE
Can't create new plugins

### ISSUE THREAD

**Issue by alexjcollins** [pixelandtonic/craftnet#153]
Getting a console error when trying to link a GitHub repo when creating a new plugin.

![Screenshot 2019-04-04 at 14 49 40](https://user-images.githubusercontent.com/12031196/55560791-e243b400-56e8-11e9-808f-1ca66481020b.png)

**Comment by benjamindavid** [comment]
Thank you for reporting the issue @alexjcollins, it should be fixed now.

**Comment by alexjcollins** [comment]
Perfect! Thanks @benjamindavid
