### ISSUE TITLE
Category links on a plugin page returns a console error

### ISSUE THREAD

**Issue by jonleverrier** [pixelandtonic/craftnet#155]
If you click on a category link towards the bottom of a plugin page, it returns a console error and does not take you to the relevant category:

```
TypeError: n.viewCategory is not a function
    at click (2f355dad55f4a0f37a5f.js:1)
    at Qt (b81b2af158206bacb977.js:2)
    at HTMLAnchorElement.n (b81b2af158206bacb977.js:2)
    at HTMLAnchorElement.Rr.c._wrapper (b81b2af158206bacb977.js:2)
```

## Steps to reproduce
1. Go to https://plugins.craftcms.com/feed-me
2. Browse to the bottom of the page
3. Try and click 1 of the 3 category links
4. Nothing happens (console error gets logged)

Tested on Chrome v73 & Firefox v66,

**Comment by benjamindavid** [comment]
Thank you for reporting this issue @jonleverrier, it should be fixed now.
