### ISSUE TITLE
Resolve plugin licensing issues in trial mode

### ISSUE THREAD

**Issue by rungta** [pixelandtonic/craftnet#162]
We have a Craft 3.1.28 install that is using project config, and hence has licenses for paid plugins in the `project.yaml` file (should we be keeping them out of it?). These licenses were purchased for the primary production domain, where things are working as expected.

We also have a staging install of the same site running on a different test domain (`*.staging.*`). We have had Craft running in trial mode on this test domain without any issues. The plugins however have started complaining of licensing issues and the control panel-wide alert to resolve the issues is one every CP page. The error under each paid plugin is:
> This licence is tied to another Craft install. Visit id.craftcms.com to resolve.

What is the best way to tackle this? Shouldn’t Craft ignore plugin licenses when running in trial mode?

**Comment by brandonkelly** [comment]
You can resolve this by ensuring that each of your environments are using the same `license.key` file as production has.
