### ISSUE TITLE
Craft ID should include EDITION for each license

### ISSUE THREAD

**Issue by kjmartens** [pixelandtonic/craftnet#164]
Well, at least for plugins that have editions. For both the developer's list of purchased licenses and the customer's list of licenses, there seems to be no indicator at any point about which edition they currently have.

**Comment by benjamindavid** [comment]
The plugin edition should now be showing up in both sections. Thanks @kjmartens!

**Comment by kjmartens** [comment]
@benjamindavid Thanks so much!
