### ISSUE TITLE
Attempting to disconnect Stripe account produces 400 error

### ISSUE THREAD

**Issue by AugustMiller** [pixelandtonic/craftnet#189]
Seems like something is amiss with the `disconnect` action, in that it won't accept the CSRF token? Tried in a couple browsers, but get:

```
POST https://id.craftcms.com/stripe/disconnect 400 (Bad Request)
```

Request:
```json
{
    "headers": {
        "X-CSRF-Token": "Redacted, but yeah, it was here! :)"
    }
}
```

Response:
```json
{
    "error": "Unable to verify your data submission."
}
```

I suspect maybe something to do with an odd object being passed to Axios, based on the `headers` key leaking into the body? 😮

**Comment by benjamindavid** [comment]
Thanks for the feedback @AugustMiller!
