### ISSUE TITLE
[FR] Make Plugin Store "Long Description" Field Searchable

### ISSUE THREAD

**Issue by ryanmasuga** [pixelandtonic/craftnet#223]
It appears the search function in the plugin store does not search the main body/description of the plugin. In order to be relevant, one must load up the keyword field. I think this makes it hard to find plugins. 

Case in point: 

1. Client asks if we knew how to integrate with the "Have I Been Pwned" DB for passwords. 
2. I knew we had used a plugin before - but I didn't remember the name. So I search "pwned" - and there are _no_ results.
3. I search "password" instead
4. Find "Password Policy" https://plugins.craftcms.com/password-policy
5. See that the word "pwned" is right there in the description
6. Cry about it in Discord
7. Come here to request that the Long Description content be made searchable

Plugin devs need to know this. We had Link Vault out there for a long time only to realize it wasn't being found for search terms that we had added to the Long Description, but not to keywords. So I had to go back and add all of those terms to the keyword field. We may have missed out on sales because I was not aware of this, and our plugin was not being found.

Maybe at least add instructions to the Long Description and Keyword fields for plugin devs, so they know how best to optimize their plugin listings.

**Comment by brandonkelly** [comment]
This is now the case, and just updated all plugins’ search keywords to include their long descriptions.

**Comment by ryanmasuga** [comment]
This is helpful and has already been useful for me - thanks!
