### ISSUE TITLE
Marking plugins as abandoned

### ISSUE THREAD

**Issue by engram-design** [pixelandtonic/craftnet#226]
### Description
Hopefully this is the right place to file this, but abandoned plugins are starting to slowly become an issue. I know it's tricky to define when a plugin might be abandoned, but I'd say for simplicities sake, it infer from Packagist.

For example: https://packagist.org/packages/kffein/plugin-license-manager is marked as abandoned, and there should be a similar notice in the plugin store.

![Screen Shot 2020-11-18 at 11 47 24 am](https://user-images.githubusercontent.com/1221575/99468077-d7a86200-2993-11eb-857f-6e6594f42c0f.png)

**Comment by johnwbaxter** [comment]
Sort of similar here in that this plugins (https://plugins.craftcms.com/amplify) repo (https://github.com/balazscsaba2006/craft3-amplify) is now set to read only, but more importantly it's not php ^7.3 compatible either.

In this very specific example, someone has forked it (https://github.com/trendyminds/craft-amplify/) and added that functionality in, but they haven't registered their version on the plugin store or indeed taken over this persons plugin to be the new maintainers.

**Comment by brandonkelly** [comment]
Possible now!

<img width="602" alt="Screenshot of a new “Abandoned” setting in Craft ID" src="https://user-images.githubusercontent.com/47792/110130303-b706eb00-7d7d-11eb-85dd-70f1677dd0a3.png">

See [Xero](https://plugins.craftcms.com/xero) and [Smart Map](https://plugins.craftcms.com/smart-map) for existing examples.
