### ISSUE TITLE
Add `perf` to `devSubdomainWords` please

### ISSUE THREAD

**Issue by nickdunn** [pixelandtonic/craftnet#256]
### Description

Could we add `perf` to `devSubdomainWords` please — we have a performance test environment that uses this in a subdomain.

Thanks!

**Comment by brandonkelly** [comment]
We debated this internally and decided against it, sorry. `perf` isn’t an established subdomain convention, and could potentially be used as an actual public subdomain, so adding it to `devSubdomainWords` would likely do more harm than good, from a licensing perspective.

If you really want to test with a `perf` subdomain, combine it with one of the supported dev subdomain words, such as `perf.testing.example.com` or `testing-perf.example.com`.
