### ISSUE TITLE
[BUG] Plugin Store only showing 6 plugins (per developer)

### ISSUE THREAD

**Issue by lindseydiloreto** [pixelandtonic/craftnet#307]
If you visit any individual developer page in the Plugin Store, it is currently only showing the **top 6 results**, instead of the developer's complete collection...

https://plugins.craftcms.com/developer/54

**Comment by bencroker** [comment]
And here I was thinking @nystudio107 had decided to sunset all but their 6 most popular plugins ;)

**Comment by AugustMiller** [comment]
Looks as though this is also affecting the category views, i.e:
https://plugins.craftcms.com/categories/ecommerce

**Comment by lindseydiloreto** [comment]
Seems to be affecting search results as well. 😬 

https://plugins.craftcms.com/search?q=seo&tab=plugins

**Comment by lindseydiloreto** [comment]
Looks like this issue worked itself out.
