### ISSUE TITLE
Switch image transform back to "Fit" (instead of "Crop")

### ISSUE THREAD

**Issue by lindseydiloreto** [pixelandtonic/craftnet#311]
Recently, all images in the Plugin Store have switched to a new image transform. Instead of `fit`, the images now use `crop`.

This leads to many images looking very broken...

---

**Blitz**
<img width="1023" alt="Blitz" src="https://user-images.githubusercontent.com/5309692/160489257-8b144f14-4308-426f-b48e-183deb6ad6b1.png">

---

**Google Maps**
<img width="1024" alt="Google Maps" src="https://user-images.githubusercontent.com/5309692/160489195-58b44100-697d-492e-b06d-321f8fc60023.png">

---

**Formie**
<img width="1021" alt="Formie" src="https://user-images.githubusercontent.com/5309692/160489223-75cdddfc-a8bc-4060-a19b-fbf73b0d05ff.png">

---

**Feed Me**
<img width="1025" alt="Feed Me" src="https://user-images.githubusercontent.com/5309692/160489274-30109cb8-13be-42a9-8a8d-79baf52ecb0a.png">

---

Very few (if any) developers have uploaded images which perfectly align with the cropped proportions. This is just a random sampling, the issue affects a majority of plugins in the store.

Could we please switch this back to a "Fit" transform? 🙏

**Comment by benjamindavid** [comment]
Thanks for the feedback @lindseydiloreto, we're looking into it 👍
