### ISSUE TITLE
Plugins display incorrect logos sometimes

### ISSUE THREAD

**Issue by BenParizek** [pixelandtonic/craftnet#50]
I've found that frequently when I search for some plugins, the incorrect logos appear for a moment before the correct logos load.

It appears to happen more often the first time I search for something, but I can't make it happen consistently. After the correct logos appear, if I search again the correct logos appear again. It seems to happen more when I first navigate to the Plugin Store tab and then run a search that I haven't run previously. Again, sometimes, but not always.

To recreate, be sure to trigger the issue during the "sometimes" moments and avoid trying to trigger the issue during the "not always" moments. =)

Searching for "Sprout" initially displays these incorrect logos:
http://share.barrelstrength.co/3c3i2M3Z2M3j

And then, shortly afterwards, but long enough after that I could snap the above screenshot, the correct logos appear:
http://share.barrelstrength.co/2Z3B3p1W3S1O

**Comment by benjamindavid** [comment]
I was seeing this too, not sure what we've changed but it seems to be working now. Do you confirm it's the case for you as well @BenParizek?

**Comment by BenParizek** [comment]
@benjamindavid I still see the issue. Often when searching:
http://share.barrelstrength.co/0c1i2i3H0Q3L

**Comment by brandonkelly** [comment]
Guessing this has been fixed for a while after some improvements to the `svg()` function made in Craft 3.0.13 and 3.0.26.
