### ISSUE TITLE
Plugin submission failing validation on id.craftcms.com results in plugin form not being re-submittable

### ISSUE THREAD

**Issue by mmikkel** [pixelandtonic/craftnet#53]
In attempting to submit a new plugin on id.craftcms.com, I encountered an issue where the form is not possible to submit after initially failing validation.

Steps to reproduce:

1. Visit the "Add a plugin" section on id.craftcms.com, select a plugin and fill out the form
2. Add a .gif file to the screenshot field
3. Submit the form (it'll fail validation due to the .gif file)
4. Remove the gif file from the screenshot field, and resubmit the form
5. The form now fails validation due to the "plugin handle being taken"
6. The plugin does not show up in the list of plugins for the account, and seems to be stuck in some sort of "half-saved" state. Even logging out/going through the whole process again results in the same error ("handle is taken")

**Comment by benjamindavid** [comment]
Now a new plugin should not be saved if there were validation errors with screenshots.
