### ISSUE TITLE
Plugin logo changed in store.

### ISSUE THREAD

**Issue by janhenckens** [pixelandtonic/craftnet#56]
I just noticed that the logo for my "Dumper" plugin changed on the store.
And when I log into id.craftcms.com it's different there too, although the package author & repo are still mine.

![screen shot 2018-03-09 at 20 31 50](https://user-images.githubusercontent.com/755428/37226034-f0b92b3a-23d8-11e8-9a5a-fd31ae7b4356.png)

It's actually using the logo for this plugin https://github.com/sjelfull/craft-dumper, which happens to have the same handle... (just cc'ing @sjelfull here, the other plugin's author)

Could you have a look at what's going wrong here?
Thanks!

**Comment by brandonkelly** [comment]
@benjamindavid maybe we should include the plugin IDs in the icon names?

**Comment by janhenckens** [comment]
A quick side note: I don't thing the other plugin is on the store, so that makes this even more confusing.

**Comment by brandonkelly** [comment]
Guessing it was created but not submitted for approval yet.
