### ISSUE TITLE
Can't select a plugin via Craft ID

### ISSUE THREAD

**Issue by marknotton** [pixelandtonic/craftnet#58]
Following the "[publishing to the Plugin Store](https://github.com/craftcms/docs/blob/v3/en/plugin-store.md)" guide; when I select a [plugin](https://github.com/marknotton/craft-plugin-agent) for submission, I get a "Couldn't load repository" popup. 

This error is returned in the console: 

```
error :
"Return value of craft\web\Application::getMutex() must be an instance of yii\mutex\FileMutex, instance of yii\redis\Mutex returned"
```
Not sure if I've missed something or this relates to the new update.

**Comment by brandonkelly** [comment]
Sorry about that. This should be fixed now.
