### ISSUE TITLE
Possibility to track license by subdomain

### ISSUE THREAD

**Issue by janhendrickx** [pixelandtonic/craftnet#61]
It would be nice to see the subdomain of the license (since we normally buy the license when the site is in development and those are all the same urls)

**Comment by brandonkelly** [comment]
Think this would end up leading to some licensing confusion – if Craft ID says a license is tied to `foo.bar.baz`, it gives the impression that it can only be used on that subdomain, when in reality it can be used on `*.bar.baz`. Thinking #76 is a better solution.
