### ISSUE TITLE
"Change domain" when editing a license doesn't allow a .group TLD (and probably others)

### ISSUE THREAD

**Issue by angrybrad** [pixelandtonic/craftnet#62]
The "Save" button when changing a domain is grayed out when it thinks it detects an invalid domain, but mydomain.group is a valid TLD.

This probably affects other TLDs as well.

On the back-end, we're already using [a library](https://github.com/layershifter/TLDExtract) for parsing domains and determining what is a [valid TLD, root domain, subdomain, etc](https://github.com/pixelandtonic/craftnet/blob/develop/src/cms/CmsLicenseManager.php#L68-L103).

We should probably just allow the value to be submitted, parse it with the library and return an error if we detect it's an invalid domain.

**Comment by benjamindavid** [comment]
The domain name is not being checked by the js app anymore.
