### ISSUE TITLE
Invalid domain name error on a valid domain name

### ISSUE THREAD

**Issue by lukehmu** [pixelandtonic/craftnet#66]
Trying to set the domain name to `rise.epwebsites.co.uk`. I've also tried `http://rise.epwebsites.co.uk`

![image 2](https://user-images.githubusercontent.com/1893145/38028373-a9993450-328a-11e8-8cdc-c96b77b41be2.png)

**Comment by brandonkelly** [comment]
@lukehmu Try `epwebsites.co.uk` instead (no subdomain), as we don’t actually track licenses to specific subdomains.

@benjamindavid Assuming that was the culprit, this should have just saved the `epwebsites.co.uk` domain on the license (the normalized domain name), and updated the UI to show the normalized value.

**Comment by brandonkelly** [comment]
Issue here is that `epwebsites.co.uk` is [considered](https://github.com/pixelandtonic/craftnet/blob/fdb8687197ec24573bfd23470f186172f3ddc8c9/config/dev-domains.php#L23) a development domain, per EP’s request. We’ll fix the error message though.
