### ISSUE TITLE
"A valid VAT ID is required" incorrect error trying to purchase Craft2

### ISSUE THREAD

**Issue by MattWilcox** [pixelandtonic/craftnet#68]
We've got a fully up-to-date project with the latest Craft and Commerce installed, gone to buy a license for Craft2 (and intending to get Commerce too after) but filling out the payment form is yielding the following error when it should not be: 

> A valid VAT ID is required for European orders

A valid VAT ID is already supplied in the form, it's the one we've used countless times to buy Craft in the past.

The actual issue turns out to be that N/A wasn't selected for the State/Province field (We're in the UK, and nothing applicable appears there when UK is selected as the country)

The error being reported is misleading.

**Comment by andris-sevcenko** [comment]
I'm not able to reproduce this. If this happens again, please send an email to support@craftcms.com referencing this issue and provide values for all address fields exactly how you're entering them.
