### ISSUE TITLE
Add "Notes" column to index view (id.craftcms.com)

### ISSUE THREAD

**Issue by lindseydiloreto** [pixelandtonic/craftnet#69]
The new "Licenses" screen is super helpful! It would be really nice if the "Notes" for each were visible from the index view...

<img width="1084" alt="notes-column" src="https://user-images.githubusercontent.com/5309692/38210512-8193cbba-366c-11e8-9946-3a784a91aec0.png">

**Comment by benjamindavid** [comment]
Thanks @lindseydiloreto!

**Comment by lindseydiloreto** [comment]
Awesome, thanks @benjamindavid! 🍺
