### ISSUE TITLE
SQL error on changing id.craftcms.com account settings

### ISSUE THREAD

**Issue by nilsenpaul** [pixelandtonic/craftnet#70]
When changing my account settings (toggle `Enable plugin developer features`), I get a SQL error on save.
If you want me to send you a screenshot of the error, let me know. It contains ID's and stuff, so I will not post it here.

**Comment by andris-sevcenko** [comment]
I'm unable to reproduce this, can you get in touch via support@craftcms.com?

**Comment by sjelfull** [comment]
This was a problem last night, but @brandonkelly said on Slack that he was looking into it.

**Comment by brandonkelly** [comment]
@sjelfull @nilsenpaul let me know if you're still experiencing this.

**Comment by sjelfull** [comment]
No, i’m all good.

—
Fred Carlsen
+47 476 51 126
Skype: sjelfull
www.superbig.co

**Comment by nilsenpaul** [comment]
Problem solved, I guess ...
