### ISSUE TITLE
Add a "Description" with the plugin name to Stripe payments

### ISSUE THREAD

**Issue by lindseydiloreto** [pixelandtonic/craftnet#74]
When receiving payments via Stripe (yay!), there is essentially no information about what the payment is _for_. If we have multiple plugins for the same price, it's impossible for us to tell (in our Stripe logs) which plugin we just got paid for.

Could you please add some information to the Stripe "Description"?

**Email:**
<img width="610" alt="stripe-email" src="https://user-images.githubusercontent.com/5309692/38514656-a3aca706-3be6-11e8-8b7c-ef43020193c3.png">

**Stripe Account:**
<img width="470" alt="stripe-login" src="https://user-images.githubusercontent.com/5309692/38514657-a3d163ca-3be6-11e8-80b5-d7413a87564f.png">

**Comment by brandonkelly** [comment]
Will ask Stripe for clarification, but it doesn't look like the [Create a transfer](https://stripe.com/docs/api#create_transfer) API provides a way for us to set the Description.

@lindseydiloreto are you able to view any of the transfer metadata (e.g. `order_number`)? If so we could at least add the info there.

**Comment by brandonkelly** [comment]
If that’s all you’re seeing then the additional metadata won’t help. There was already some custom metadata values that aren’t showing up in your screenshot.

**Comment by brandonkelly** [comment]
They got me sorted 🎉

**Comment by lindseydiloreto** [comment]
Woohoo! Thanks @brandonkelly, can't wait to see it in action!  👏

**Comment by lindseydiloreto** [comment]
It works!!   🚀

<img width="611" alt="stripe-email-smart-map" src="https://user-images.githubusercontent.com/5309692/38681684-23bb6d4a-3e1e-11e8-88e4-344fd6564a6e.png">
<img width="424" alt="stripe-login-smart-map" src="https://user-images.githubusercontent.com/5309692/38681685-240f039c-3e1e-11e8-8702-29ce484cf0ce.png">

**Comment by brandonkelly** [comment]
Yay!
