### ISSUE TITLE
Payment won't process, but no error is shown

### ISSUE THREAD

**Issue by khalwat** [pixelandtonic/craftnet#75]
I'm logged into a client's Craft ID, which has credit card and billing info filled out by the client.

I add the appropriate plugins to the card, click Process Payment... and then on the Payment screen, I click **Pay $217.00** and I see a spinner... then nothing happens. The spinner goes away. No error message is shown.

I check the client's Craft ID and no plugins are listed, so presumably they haven't been billed.

If it matters, this is running in an incognito window in Chrome 65.

**Comment by brandonkelly** [comment]
Fixed via 0aded653c2831cbd5b5e686ab14a0f34c0487aca and craftcms/cms@0a21231c6cafed007ea8430a5580c2217576444d.

**Comment by khalwat** [comment]
Just to follow up on this -- the issue was fixed with Craft CMS 3.0.3; no error message was display (which is what the fix seemed to be about) but the payment went through properly (maybe due to retries).

So just confirming the fix, nice job!
