### ISSUE TITLE
[FR] Display 'Active installs' in Developer > Plugins

### ISSUE THREAD

**Issue by ben-callaway** [pixelandtonic/craftnet#81]
It would be handy to display this figure on the plugin page (https://id.craftcms.com/developer/plugins). At a glance you would be able to see active installs for all your developer plugins.  Currently the only place to view this information is by manually going through each plugin within the plugin store.

Example:

<img width="1138" alt="active-installs" src="https://user-images.githubusercontent.com/7083462/39254925-3856d80e-48a3-11e8-867f-20f153a5b05c.png">

**Comment by benjamindavid** [comment]
Thanks @ben-callaway!
